-- Drop and recreate Users table (Example)

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS to_dos CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY  NOT NULL AUTO_INCREMENT,
  username VARCHAR(255) NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE to_dos (
  id SERIAL PRIMARY KEY NOT NULL AUTO_INCREMENT,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  description VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  complete BOOLEAN
);
